CREATE DATABASE IF NOT EXISTS testapp;
USE testapp;
CREATE TABLE IF NOT EXISTS testapp.MyGuests (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR (10) NOT NULL,
    lastname VARCHAR (10) NOT NULL,
    phone VARCHAR (15) NOT NULL,
    dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);

